export enum Config {
    PORT = 'PORT',
    HOST = 'HOST',
    APP_URL = 'APP_URL',
    DATABASE_URL = 'DATABASE_URL',
    GRAPHQL_DEBUG = 'GRAPHQL_DEBUG',
    SECRET_JWT = 'SECRET_JWT',
    SECRET_SALT = 'SECRET_SALT',
    HASH_SALT = 'HASH_SALT',
    THROTTLE_TTL = 'THROTTLE_TTL',
    THROTTLE_LIMIT = 'THROTTLE_LIMIT',
    TOKEN_EXPIRE_TIME = 'TOKEN_EXPIRE_TIME',
    TOKEN_SECRET_KEY = 'TOKEN_SECRET_KEY'
}
